# Generated by Django 4.2.4 on 2023-08-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('MinimumHeight', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('MaximumCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TimeField()),
                ('ShowID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='park_app.show')),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('RideID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='park_app.ride')),
                ('StallID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='park_app.stall')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('TicketNo', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Parking_used', models.BooleanField()),
                ('BookedRide', models.ManyToManyField(blank=True, related_name='participants', to='park_app.ride')),
                ('BookedShow', models.ManyToManyField(blank=True, related_name='audience', to='park_app.showing')),
            ],
        ),
    ]
