# Generated by Django 4.2.2 on 2023-08-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='Description',
            field=models.CharField(default="It's a Stall", max_length=100),
        ),
    ]
